add_library(inputrack_platform STATIC src/VirtualMicrophone.cpp)
if(WIN32)
    target_sources(inputrack_platform PRIVATE src/VirtualMicrophone_windows.cpp)
    target_link_libraries(inputrack_platform PRIVATE setupapi ksuser)
endif()
target_include_directories(inputrack_platform PUBLIC include)
target_link_libraries(inputrack_platform PUBLIC juce::juce_audio_basics)
